version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: intranet_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: intranet
      POSTGRES_PASSWORD: intranet_pass
      POSTGRES_DB: intranet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
